In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


file = pd.read_excel("/Users/maggie/Documents/vgsales/VideoGames_Sales.xlsx")
file.head()

,title,console,genre,publisher,developer,critic_score,total_sales(mil),na_sales(mil),jp_sales(mil),pal_sales(mil),other_sales(mil),release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06

In [2]:
print(file.isnull().sum())

title                   0
console                 0
genre                   0
publisher               0
developer              17
critic_score        57338
total_sales(mil)    45094
na_sales(mil)       51379
jp_sales(mil)       57290
pal_sales(mil)      51192
other_sales(mil)    48888
release_date         7051
dtype: int64

In [3]:
file.describe()

,critic_score,total_sales(mil),na_sales(mil),jp_sales(mil),pal_sales(mil),other_sales(mil),release_date
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000,56965
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041,2006-11-14 06:33:03.491617792
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1971-12-03 00:00:00
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000,2001-03-28 00:00:00
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000,2008-09-16 00:00:00
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000,2012-12-27 00:00:00
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000,2024-12-31 00:00:00
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643,NaN

In [ ]:
# looking at caterogical variables, columns that are not numbers

categorical_cols = file.select_dtypes(include='object').columns #getting the different columns

# for each column in the dataset, we want to know how many unique, and how mant of that row
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(file[col].value_counts().head(12))

Column: title
title
Plants vs. Zombies     17
Pac-Man                16
Monopoly               15
Doom                   14
Double Dragon          14
Elite                  14
Minecraft              13
Resident Evil 4        13
Jeopardy!              13
Lemmings               13
Samurai Shodown        13
The Incredible Hulk    12
Name: count, dtype: int64

Column: console
console
PC      12617
PS2      3565
DS       3288
PS4      2878
PS       2707
NS       2337
XBL      2120
PSN      2004
XOne     1963
PS3      1905
PSP      1807
X360     1735
Name: count, dtype: int64

Column: genre
genre
Misc            9304
Action          8557
Adventure       6260
Role-Playing    5721
Sports          5586
Shooter         5410
Platform        4001
Strategy        3685
Puzzle          3521
Racing          3425
Simulation      3158
Fighting        2367
Name: count, dtype: int64

Column: publisher
publisher
Unknown                        8842
Sega                           2207
Ubisoft                        1663
Electronic Arts                1619
Activision                     1582
Konami                         1544
Nintendo                       1476
Sony Computer Entertainment    1372
Microsoft                      1272
THQ                            1111
Capcom                         1092
Atari                           839
Name: count, dtype: int64

Column: developer
developer
Unknown            4435
Konami              976
Sega                915
Capcom              870
Namco               489
Square Enix         425
SNK Corporation     408
EA Canada           396
Hudson Soft         394
Ubisoft             377
Bandai              336
Nintendo            327
Name: count, dtype: int64